image: node:7
clone:
  depth: 200
pipelines:
  branches:
    main:
      - step:
          script:
            - git push https://heroku:$HEROKU_API_KEY@git.heroku.com/flamingo-blog.git HEAD
    dev:
      - step:
          script:
            - git push https://heroku:$HEROKU_API_KEY@git.heroku.com/flamingo-blog.git dev:main
