export default {
    ourusers: 'Os Nossos Utilizadores',
    features: 'Funcionalidades',
    security: 'Segurança',
    blog: 'Blog',
    contact_support_link: 'Contactar o Apoio',
    contact_us: 'Contacte-nos',
    privacy_notice : 'Política de Privacidade',
    terms_of_use : 'Termos de Utilização',
    support: 'Apoio',
    footer_text : "O rastreio e a contagem de Flamingo são apenas para efeitos de informação.",
    footer_text2 : "Consulte sempre o seu advogado e o seu contabilista no que respeita aos requisitos específicos do seu estatuto de residência e de visto.",

    footer_made_in: "Desenvolvido no Reino Unido",
    footer_copyright: "©2022 — 2024 Taboo Media Limited. Registado em Inglaterra",
    footer_copyright2: "Número da empresa: 12461952. Todos os direitos reservados.",
    footer_copyright3: "A aplicação Flamingo é uma marca registada da Taboo Media Limited.",


    pagination_prev : "Anterior",
    pagination_next: "Seguinte",

    download : "Descarregar",
    download_now : "Flamingo Agora",
    download_text : "Uma ferramenta essencial para expatriados internacionais, residentes em permanência, residentes em dois estados e viajantes frequentes.",

    faq : "Perguntas Frequentes",
    faq_short : "FAQ",
    faq_text : "Encontre respostas rápidas a perguntas frequentes sobre a utilização da aplicação Flamingo.",
    faq_q1 : 'Porque tenho de definir os Serviços de localização como “Sempre"?',
    faq_q2 : "Porque tenho de abrir a aplicação todos os meses?",
    faq_q3 : "Conseguem ter acesso à minha localização exata em qualquer altura?",
    faq_q4 : "Posso adicionar o meu histórico de viagens anteriores à instalação da aplicação?",
    faq_q5 : "Posso utilizar Flamingo gratuitamente?",
    faq_q6 : "Posso monitorizar as minhas viagens para países distintos do Reino Unido (Inglaterra, Escócia, País de Gales e Irlanda do Norte) separadamente do Reino Unido?",
    faq_q7 : "Existe uma versão para Android?",

    faq_a1:  'Para ser possível efetuar um acompanhamento automático e preciso das viagens, é essencial configurar os Serviços de Localização para “Sempre” em vez de “Durante a utilização da aplicação”. Desta forma, o Flamingo pode seguir os seus movimentos em segundo plano, mesmo quando não estiver a utilizar a aplicação, eliminando a necessidade de iniciar a aplicação sempre que atravessar a fronteira de um país ou estado. Pode ficar descansado, foram realizados testes exaustivos para garantir um consumo mínimo da bateria com esta configuração de localização.',
    faq_a2:  'Recomendamos que abra a aplicação com uma periodicidade mensal, uma vez que o sistema operativo do iPhone pode bloquear a funcionalidade de seguimento de uma aplicação por inatividade. A abertura regular do Flamingo garante a monitorização contínua e precisa das viagens, sem interrupções.',
    faq_a3:  'Pode ficar tranquilo, todos os dados introduzidos ou registados automaticamente na aplicação são encriptados pela Apple e armazenados exclusivamente no seu dispositivo ou nos serviços de dados seguros da Apple (iCloud), dependendo das definições da sua aplicação. Não temos acesso nem armazenamos os seus dados nos nossos servidores e é por isso que não requeremos o registo na aplicação. Além disso, o Flamingo nunca monitoriza a sua localização exata. Apenas utilizamos a geolocalização ao nível da cidade para determinar a sua localização geral, com o objetivo de registar os seus movimentos entre países, estados dos EUA e cidades. Esta abordagem garante-lhe total privacidade e praticamente não tem impacto na carga da sua bateria. ',
    faq_a4:  'Sim, pode adicionar a informação das suas viagens anteriores à aplicação. Há duas formas de o fazer: adicionar manualmente cada uma das suas viagens à sua cronologia, ou, se costuma tirar muitas fotografias, pode reconstruir automaticamente o seu histórico de viagens digitalizando a sua biblioteca de fotografias. Não transferimos nem vemos nenhuma das suas fotografias; apenas digitalizamos a localização e as informações de data e hora, pelo que o processo de digitalização demora apenas alguns minutos.',
    faq_a5:  "Na versão gratuita da aplicação Flamingo, pode introduzir até cinco entradas de viagem. Isto inclui tanto as viagens introduzidas manualmente (viagens concluídas) como as viagens automaticamente registadas (novas viagens). Quando atingir este limite, terá de eliminar algumas das entradas existentes para adicionar novas entradas ou considerar a hipótese de atualizar para uma subscrição paga, na qual terá acesso à funcionalidade ilimitada de monitorização e relatório de viagens.",
    faq_a6:  "Sim, tem a opção de registar cada um dos países pertencentes ao Reino Unido (Inglaterra, Escócia, etc.) separadamente ou combiná-los e registar todas as visitas como Reino Unido. Além disso, pode registar as suas visitas às ilhas de Jersey e Guernsey separadamente das do Reino Unido continental.",
    faq_a7:  "A aplicação Flamingo ainda não está disponível para Android, mas estamos a trabalhar ativamente no seu desenvolvimento. Fique atento às atualizações!",

    features_title : "Funcionalidades",
    features_10reasons : "O Monitor de Viagens Indispensável",
    features_10reason_text : "Uma ferramenta essencial para expatriados internacionais, residentes em permanência, residentes em dois estados e viajantes frequentes.",
    features_auto : "Registo",
    features_record : 'Automático de Viagens',
    features_record_text  : "O Flamingo deteta automaticamente quando atravessa uma fronteira e regista com precisão os detalhes da sua viagem. ",

    features_plan : "Planear Viagens Futuras",
    features_plan_title : "Planear Viagens Futuras",
    features_plan_subtitle : "Planeie o seu ano inteiro adicionando as próximas viagens à aplicação. Uma vez lá, o Flamingo seguirá os seus movimentos e ajustará as datas conforme necessário.",
    features_plan_text : "",

    features_store: "Armazenar Documentos e Detalhes de Viagem",
    features_store_title: "Armazenar Documentos e Detalhes de Viagem",
    features_store_subtitle: "Mantenha as suas viagens organizadas, adicionando notas detalhadas e guardando todos os documentos relevantes num único local. Esta opção é especialmente útil se precisar de apresentar provas das suas viagens a advogados, contabilistas ou autoridades governamentais.",
    features_store_text: "",

    features_residency : "Estatuto de",

    features_dom_status : "Residência e Domicílio",

    features_dom_text : "Quer pretenda estabelecer, manter ou evitar um domicílio ou estatuto de residência, o Flamingo tem tudo o que precisa. Defina um limite e um período de monitorização e controle a sua presença física no país ou num estado dos EUA.",
    features_tax :"Avaliação",
    features_tax_residency : "de Residência",
    features_tax_title: "Avaliação de Residência Fiscal",
    features_tax_subtitle: "O Flamingo determina automaticamente a probabilidade de adquirir o estatuto de residente fiscal na maioria dos países, estados e cidades dos EUA, com base nas regras fiscais internacionais. A avaliação da residência fiscal é baseada na presença física, bem como em critérios adicionais comumente usados pelas autoridades locais, como o seu rendimento, bens e laços familiares.",
    features_tax_text: "",

    features_assessment: "Fiscal",

    features_coming_soon: "Brevemente",
    features_usa : "Estados dos EUA",
    features_day_count : "Contagem de Dias",
    features_usa_text : "Se for residente em dois estados ou se apenas viajar frequentemente entre estados dos EUA, o Flamingo registará e contará automaticamente quantos dias passa em cada estado para determinar a sua presença física para efeitos de domicílio e residência estadual.",
    features_schengen : "Calculadora",
    features_calculator: "Espaço Schengen",
    features_calculator_text : "A calculadora do Espaço Schengen integrada do Flamingo utiliza os dias acumulados passados nos países do espaço Schengen, indicando os dias que lhe restam e permitindo-lhe planear futuras viagens à UE com base na regra dos 90/180 dias.",

    features_short_term : "Monitorização de Vistos de Curta Duração",
    features_short_term_title : 'Monitorização de Vistos de Curta Duração',
    features_short_term_subtitle : 'Adicione os detalhes do seu visto de curta duração e as condições de acesso sem necessidade de visto, e a aplicação Flamingo acompanhará automaticamente as suas entradas e estadias no país, alertando-o quando se aproximar dos seus limites.',
    features_short_term_text : '',

    features_new_york : "Contagem de Dias nas Cidades dos EUA",
    features_new_york_title : "Contagem de Dias nas Cidades dos EUA",
    features_new_york_subtitle : 'Reconhecemos a importância de cumprir as regras fiscais locais e estaduais nos Estados Unidos, e é por essa razão que agora disponibilizamos um registo individual dos dias de estadia em cada cidade dos EUA. Por exemplo, pode configurar a residência fiscal e monitorizar as suas visitas aos cinco bairros de Nova Iorque - Manhattan, Brooklyn, Queens, Bronx e Staten Island - separadamente das suas estadias no Estado de Nova Iorque. \Estamos a adicionar continuamente mais cidades dos EUA à aplicação para melhorar a sua experiência.',
    features_new_york_text : "",

    features_build_in : "Índice de Passaportes",
    features_build_in_title : 'Índice de Passaportes',
    features_build_in_subtitle : 'Consulte os requisitos de visto de qualquer país introduzindo a(s) sua(s) nacionalidade(s) na aplicação. Descubra onde pode viajar sem visto, ou se precisa de um visto em papel, um visto eletrónico ou um visto à chegada. Esta ferramenta simplifica o seu planeamento de viagens, garantindo que está sempre preparado para o seu próximo destino.',
    features_build_in_text: 'Nota: Estas informações têm um caráter meramente indicativo e não devem ser consideradas como aconselhamento jurídico. Consulte sempre as fontes oficiais antes de planear a sua viagem.',

    features_export : "Exportar",
    features_reports : "Relatórios",
    features_reports_title : "Exportar Relatórios",
    features_reports_subtitle : "Exporte relatórios em formato CSV personalizáveis que detalham o seu historial de viagens para efeitos de domicílio e residência. Estes relatórios, desenvolvidos em colaboração com advogados e contabilistas, facilitam a declaração de impostos e a conformidade com a imigração. Partilhe-os com as autoridades e os profissionais de direito para simplificar as suas necessidades de documentação.",
    features_reports_text : "",

    how_security: "Segurança",
    how_text : "A sua Privacidade é a Nossa Prioridade",
    how_important : "Notificações",
    how_notifications : "Importantes",
    how_notify_text : "O Flamingo alerta-o quando está a atingir o limite de residência, o limite de permanência sem visto ou a data de expiração do visto, evitando assim quaisquer problemas com as autoridades.",
    how_privacy : "Privacidade",
    how_complete: "Completa",
    how_complete_text : "Os seus dados de viagem, residência e vistos são armazenados apenas localmente no seu dispositivo. Não recolhemos nem armazenamos as suas informações nos nossos servidores.",
    how_complete_text2 : "*Com o Flamingo PRO pode sincronizar os seus dados através do iCloud em todos os seus dispositivos.",
    how_bank_level  : "Segurança de Dados de",
    how_data_security : "Nível Bancário",
    how_bank_text : "O Flamingo utiliza várias camadas de backups de dados, garantindo a segurança das suas valiosas informações de viagem.",

    help_you : "Flamingo ajuda-o com:",
    help1: 'Teste da Presença Substancial e Teste da Presença Física dos EUA.',
    help2: 'Teste de Residência Legal (SRT) do Reino Unido',
    help3: 'Monitorização da regra dos 90/180 dias do Espaço Schengen da UE',
    help4: 'Teste de Residência Fiscal de França',
    help5: 'Regra dos 90 dias da Suíça',
    help6: 'Requisitos de residência / presença física do Canadá',
    help7: 'Lei 60 (Lei 20/22) de contagem de dias de Porto Rico',
    help8: 'Contagem de dias para efeitos do estatuto de residência da Índia',
    help9: 'Contagem de dias para efeitos do estatuto de residência da Malásia',
    help10: 'Regra da presença física da África do Sul',
    help11: 'Contagem de dias para efeitos de residência do Chipre',
    help12: 'Residência de Israel',
    help13: 'Regra dos 183 dias de Itália, regra dos 183 dias da Austrália, regra dos 183 dias de Espanha, regra dos 183 dias do Brasil',
    help14: 'Regra dos 325 dias da Nova Zelândia',
    help15: 'Regra dos 60 dias do Chipre',

    index_who_need : "Quem precisa do Flamingo?",
    index_expats: "Expatriados &",
    index_expats_nomads : "Nómadas Digitais",
    index_expats_texts : "Flamingo controla o número de dias e noites passados no seu país de residência, provando ser uma ferramenta essencial para expatriados de todo o mundo, proprietários de casas no estrangeiro, nómadas digitais e residentes permanentes que procuram uma forma eficiente de gerir as suas obrigações de residência.",
    index_tax : "Residentes",
    index_residents : "Fiscais",
    index_residents_text : "A aplicação Flamingo simplifica a gestão da residência fiscal, monitorizando automaticamente os seus dias de viagem e alertando-o quando se aproxima dos limites de residência. Também fornece relatórios detalhados e desenvolvidos por especialistas para facilitar a sua partilha com as autoridades, consultores fiscais e contabilistas.",
    index_frequent_travelers : "Viajantes Frequentes",
    index_ft_text : "Flamingo regista automaticamente as suas passagens de fronteira nos diferentes países e estados dos EUA, ao mesmo tempo que controla diligentemente os seus vistos e limites de estadia sem visto. Quer viaje em trabalho ou em lazer, a aplicação permite-lhe ver e gerir o seu histórico de viagens, adicionar detalhes e planear as próximas viagens.",
    index_i : "Estudantes",
    index_s : "Internacionais",
    index_is_text : "Flamingo simplifica a vida dos estudantes internacionais, gerindo as estadias num país estrangeiro e supervisionando o cumprimento dos requisitos dos vistos de estudante. As suas capacidades de planeamento de viagens futuras permitem organizar as viagens de forma eficiente, garantindo um equilíbrio entre os estudos e a exploração ou as visitas a casa.",

    about_page :  "Sobre",

    contact_support: "Apoio na Aplicação",
    contact_text : "Se já for utilizador da aplicação Flamingo, recomendamos que nos contacte através das configurações da aplicação, para que possamos estar melhor equipados para o ajudar",
    contact_go_to : "Entre na Aplicação",
    contact_dsc : "Utilize este formulário para efetuar um pedido de assistência ou para nos enviar os seus comentários.",
    contact_name : "O Seu Nome",
    contact_email: "Endereço de E-mail",
    contact_model : "Modelo de iPhone",
    contact_select_model : "Selecionar Modelo",
    contact_version : "Versão iOS",
    contact_select_version : "Selecionar Versão",
    contact_message : "Mensagem",
    contact_message_placeholder : "Introduza a sua mensagem",
    contact_submit : "Submeter",
    contact_send_result : "Enviado!",
    contact_send_text : "Agradecemos a sua mensagem! Será contactado brevemente por um elemento da nossa equipa.",

    error_text: "Algo correu mal. Por favor, tente novamente.",
    error_try: "Tente Novamente",
    error_email: "Por favor, introduza o seu endereço de e-mail no formato correto: oseunome@empresa.com",
    error_name: "Por favor, introduza o seu nome",
    to_upload : "Clique aqui",
    or_drop: "ou arraste e largue para carregar ficheiros",

    blog_back : "Voltar aos Artigos",
    blog_stories: "Histórias e Entrevistas",
    blog_text_2 : "As últimas notícias, dicas de viagem e truques da nossa equipa.",
    blog_related : "Publicações Relacionadas",
    blog_text : "As últimas notícias, dicas de viagem e truques da nossa equipa.",
    blog_view_all : "Ver todas as publicações",
    blog_published : "Publicadas",

    page: "Página",
    go_back : "Voltar atrás"



}
