export default {
    ourusers: 'Nuestros usuarios',
    features: 'Funcionalidades',
    security: 'Seguridad',
    blog: 'Blog',
    contact_support_link: 'Contactar con Soporte',
    contact_us: 'Contáctanos',
    privacy_notice : 'Aviso de privacidad',
    terms_of_use : 'Condiciones de uso',
    support: 'Soporte',
    footer_text : "El seguimiento y recuento de Flamingo se crean solo con fines informativos.",
    footer_text2 : "Consulta siempre con tu asesor jurídico y fiscal sobre los requisitos específicos de tu situación de residencia y visado.",

    footer_made_in: "Hecha en el Reino Unido.",
    footer_copyright: "©2022 — 2024 Taboo Media Limited. Registrada en Inglaterra",
    footer_copyright2: "Número de empresa: 12461952. Todos los derechos reservados.",
    footer_copyright3: "Flamingo App es una marca comercial de Taboo Media Limited.",


    pagination_prev : "Anterior",
    pagination_next: "Siguiente",

    download : "Descarga",
    download_now : "Flamingo Ahora",
    download_text : "Una herramienta esencial para expatriados, residentes permanentes, residentes en dos estados y viajeros frecuentes.",

    faq : "Preguntas más frecuentes",
    faq_short : "FAQ",
    faq_text : "Encuentra respuestas rápidas a preguntas comunes sobre el uso de la aplicación Flamingo.",
    faq_q1 : '¿Por qué tengo que configurar los servicios de localización en "Siempre"?',
    faq_q2 : "¿Por qué tengo que abrir la aplicación cada mes?",
    faq_q3 : "¿Se puede ver mi ubicación exacta en un momento dado?",
    faq_q4 : "¿Puedo añadir mi historial de viajes anteriores a la instalación de la aplicación?",
    faq_q5 : "¿Puedo utilizar Flamingo gratis?",
    faq_q6 : "¿Puedo hacer el seguimiento de mis viajes a los distintos países del Reino Unido (Inglaterra, Escocia, Gales, Irlanda del Norte) por separado?",
    faq_q7 : "¿Tenéis una versión para Android?",

    faq_a1:  'Para un seguimiento automático preciso de los viajes, es esencial configurar los Servicios de Localización en "Siempre" en lugar de "Mientras se utiliza la aplicación". Esto asegura que Flamingo pueda seguir tus movimientos en segundo plano, incluso cuando la aplicación está cerrada, eliminando la necesidad de abrir la aplicación cada vez que cruzas la frontera de un país o estado. Ten por seguro que se han realizado pruebas exhaustivas para garantizar un uso mínimo de la batería con esta configuración de ubicación.',
    faq_a2:  'Recomendamos abrir la aplicación aproximadamente cada mes, ya que el sistema operativo del iPhone puede bloquear la función de seguimiento de una aplicación debido a la inactividad. Abrir regularmente Flamingo garantiza un seguimiento continuo y preciso de los viajes sin interrupciones.',
    faq_a3:  'Ten por seguro que todos los datos introducidos o registrados automáticamente en la app son encriptados por Apple y almacenados únicamente en tu dispositivo o en los servicios de datos seguros de Apple (iCloud), dependiendo de la configuración de tu app. No tenemos acceso ni almacenamos tus datos en nuestros servidores y por eso no exigimos que te registres en la app. Además, Flamingo nunca rastrea tu ubicación exacta. En su lugar, utilizamos la geolocalización a nivel de ciudad para determinar tu ubicación general con el fin de registrar tus movimientos entre países, estados de EE.UU. y ciudades. Este enfoque garantiza tu total privacidad y apenas afecta a la carga de la batería. ',
    faq_a4:  'Sí, puedes añadir la información de tus viajes anteriores a la aplicación. Hay dos formas de hacerlo: añadir manualmente cada viaje a tu cronología uno a uno, o si sueles hacer muchas fotos, puedes reconstruir automáticamente tu historial de viajes escaneando tu Galería de fotos. No subimos ni vemos ninguna de tus fotos; solo escaneamos su ubicación e información de fecha y hora, por lo que el proceso de escaneado solo lleva unos minutos.',
    faq_a5:  "Como usuario gratuito de la aplicación Flamingo, puedes introducir hasta cinco entradas de viajes. Esto incluye tanto los viajes introducidos manualmente (viajes completados) como los rastreados automáticamente (viajes nuevos). Una vez que alcances este límite, tendrás que eliminar algunas de las entradas existentes para añadir otras nuevas o considerar la posibilidad de actualizar a una suscripción de pago para el seguimiento ilimitado de viajes y la función de informes.",
    faq_a6:  "Sí, tienes la opción de hacer un seguimiento de cada uno de los países del Reino Unido (Inglaterra, Escocia, etc.) por separado o combinarlos y registrar todas las visitas como Reino Unido. Además, puedes registrar tus visitas a las islas de Jersey y Guernsey por separado del Reino Unido continental.",
    faq_a7:  "La aplicación Flamingo aún no está disponible en Android, pero estamos trabajando activamente en su desarrollo. Mantente al tanto de las novedades.",

    features_title : "Funcionalidades",
    features_10reasons : "El rastreador de viajes definitivo",
    features_10reason_text : "Una aplicación esencial para expatriados, residentes permanentes, propietarios de viviendas en el extranjero y viajeros frecuentes.",
    features_auto : "Registro de viaje",
    features_record : 'automático',
    features_record_text  : "Flamingo determina automáticamente cuándo cruzas la frontera y registra con precisión los detalles de tu viaje. ",

    features_plan : "Planifica futuros viajes",
    features_plan_title : "Planifica futuros viajes",
    features_plan_subtitle : "Planifica todo el año añadiendo tus próximos viajes a la aplicación. Una vez allí, Flamingo hará un seguimiento de tus movimientos y ajustará las fechas según sea necesario.",
    features_plan_text : "",

    features_store: "Almacena documentos y detalles de viaje",
    features_store_title: "Almacena documentos y detalles de viaje",
    features_store_subtitle: "Mantén tus viajes organizados añadiendo notas detalladas y almacenando todos los documentos relevantes en un único lugar. Esto es especialmente útil si necesitas presentar pruebas de tus viajes a abogados, asesores fiscales o autoridades gubernamentales.",
    features_store_text: "",

    features_residency : "Estado de residencia",

    features_dom_status : "domicilio",

    features_dom_text : "Tanto si buscas establecer, mantener o evitar un estado de domicilio o residencia, Flamingo te lo pone fácil. Establece un umbral y un periodo de seguimiento y controla tu presencia física en un país o estado de EE.UU. ",
    features_tax :"Evaluación",
    features_tax_residency : "de la residencia",
    features_tax_title: "Evaluación de la residencia fiscal",
    features_tax_subtitle: "Flamingo determina automáticamente la probabilidad de que adquieras el estatus de residente fiscal en la mayoría de los países, estados y ciudades de EE.UU. basándose en las normas fiscales internacionales. La evaluación de la residencia fiscal se basa en la presencia física, así como en criterios adicionales utilizados habitualmente por las autoridades locales, como tus ingresos, propiedades y lazos familiares.",
    features_tax_text: "",

    features_assessment: "fiscal",

    features_coming_soon: "Próximamente",
    features_usa : "Recuento de días en",
    features_day_count : "estados de EE.UU.",
    features_usa_text : "Si resides en dos estados o solo viajas con frecuencia entre estados de EE.UU., Flamingo registrará y contará automáticamente cuántos días pasas en cada estado para determinar tu presencia física a efectos de domicilio y residencia estatal.",
    features_schengen : "Calculadora",
    features_calculator: "del espacio Schengen",
    features_calculator_text : "La calculadora Schengen integrada de Flamingo utiliza los días acumulados en los países Schengen para mostrar los días que te quedan y te permite planificar futuros viajes a la UE basándose en la regla de los 90/180 días.",

    features_short_term : "Seguimiento de visados de corta duración",
    features_short_term_title : 'Seguimiento de visados de corta duración',
    features_short_term_subtitle : 'Añade los datos de tu visado de corta duración y las condiciones de acceso sin visado, y la aplicación Flamingo hará un seguimiento automático de tus entradas y estancias en el país, avisándote cuando te acerques a tus límites.',
    features_short_term_text : '',

    features_new_york : "Recuento de días en ciudades de EE.UU.",
    features_new_york_title : "Recuento de días en ciudades de EE.UU.",
    features_new_york_subtitle : 'Somos conscientes de la importancia de cumplir las normativas fiscales estatales y locales en Estados Unidos, por lo que ahora ofrecemos un seguimiento diario independiente para cada ciudad estadounidense. Por ejemplo, puedes establecer la residencia fiscal y hacer un seguimiento de tus visitas a los cinco distritos de Nueva York (Manhattan, Brooklyn, Queens, el Bronx y Staten Island) independientemente de tus estancias en el estado de Nueva York. \n\n Continuamente vamos añadiendo más ciudades de EE.UU. a la aplicación para mejorar tu experiencia.',
    features_new_york_text : "",

    features_build_in : "Índice de pasaportes",
    features_build_in_title : 'Índice de pasaportes',
    features_build_in_subtitle : 'Busca los requisitos de visado para cualquier país introduciendo tu(s) nacionalidad(es) en la aplicación. Averigua a dónde puedes viajar sin visado o si necesitas un visado en papel, un visado electrónico o un visado a la llegada. Esta herramienta simplifica la planificación de tus viajes, garantizando que siempre estés preparado para tu próximo destino.',
    features_build_in_text: 'Nota: Esta información es orientativa y no debe considerarse asesoramiento jurídico. Antes de planificar un viaje, consulta siempre con fuentes oficiales.',

    features_export : "Exporta",
    features_reports : "informes",
    features_reports_title : "Exporta informes",
    features_reports_subtitle : "Exporta informes CSV personalizables que detallan tu historial de viajes por domicilio y residencia. Estos informes, desarrollados en consulta con abogados y asesores fiscales, garantizan la facilidad de la declaración de impuestos y el cumplimiento de las normas de inmigración. Compártelos con autoridades y profesionales jurídicos para simplificar tus necesidades de documentación.",
    features_reports_text : "",

    how_security: "Seguridad",
    how_text : "Tu privacidad es nuestra prioridad",
    how_important : "Notificaciones",
    how_notifications : "importantes",
    how_notify_text : "Flamingo te avisa cuando alcanzas el umbral de residencia, los límites de estancia sin visado o las fechas de caducidad del visado, para ayudarte a evitar problemas con las autoridades.",
    how_privacy : "Privacidad",
    how_complete: "Completo",
    how_complete_text : "Tus datos de viaje, residencia y visado se almacenan localmente solo en tu dispositivo. No recopilamos, ni almacenamos, tu información en nuestros servidores. ",
    how_complete_text2 : "*Con Flamingo PRO puedes sincronizar tus datos a través de iCloud en todos tus dispositivos.",
    how_bank_level  : "Seguridad de datos",
    how_data_security : "de nivel bancario",
    how_bank_text : "Flamingo emplea múltiples capas de copias de seguridad de datos, lo que garantiza la tranquilidad de tu valiosa información de viaje.",

    help_you : "Flamingo te ayuda con:",
    help1: 'EE.UU.: Prueba de presencia sustancial y prueba de presencia física en EE.UU.',
    help2: 'Reino Unido: Prueba de residencia legal en el Reino Unido (SRT)',
    help3: 'Espacio Schengen: Seguimiento en el espacio Schengen de la UE, regla de los 90 en 180 días',
    help4: 'Francia: Prueba de residencia fiscal en Francia',
    help5: 'Suiza: Regla de los 90 días en Suiza',
    help6: 'Canadá: Requisitos de residencia y presencia física en Canadá',
    help7: 'Puerto Rico: Recuento de días de la Ley 60 (ley 20/22)',
    help8: 'India: Recuento de días de residencia en la India',
    help9: 'Malasia: Recuento de días de residencia en Malasia',
    help10: 'Sudáfrica: Regla de Sudáfrica sobre presencia física',
    help11: 'Chipre: Recuento de días de residencia en Chipre',
    help12: 'Israel: Residencia en Israel',
    help13: 'Regla de los 183 días para Italia, regla de los 183 días para Australia, regla de los 183 días para España, regla de los 183 días para Brasil',
    help14: 'Nueva Zelanda: Regla de los 325 días',
    help15: 'Regla de los 60 días en Chipre',

    index_who_need : "¿Quién necesita Flamingo?",
    index_expats: "Expatriados y",
    index_expats_nomads : "nómadas digitales",
    index_expats_texts : "Flamingo controla el número de días y noches que pasas en tu país de residencia, lo que la convierte en una herramienta esencial para expatriados, propietarios de viviendas en el extranjero, nómadas digitales y residentes permanentes que buscan una forma eficaz de gestionar sus obligaciones de residencia.",
    index_tax : "Residentes",
    index_residents : "fiscales",
    index_residents_text : "La aplicación Flamingo simplifica la gestión de la residencia fiscal mediante el seguimiento automático de tus días de viaje y te avisa cuando te acercas a los umbrales de residencia. También proporciona informes detallados elaborados por expertos para compartirlos fácilmente con autoridades, asesores fiscales y contables.",
    index_frequent_travelers : "Viajeros frecuentes",
    index_ft_text : "Flamingo registra automáticamente tus cruces fronterizos a diferentes países y estados de EE.UU., al tiempo que realiza un seguimiento diligente de tus visados y límites de estancia sin visado. Tanto si viajas por negocios como por placer, la aplicación te permite ver y gestionar tu historial de viajes, añadir detalles y planificar próximos viajes. ",
    index_i : "Estudiantes",
    index_s : "internacionales",
    index_is_text : "Flamingo simplifica la vida de los estudiantes internacionales gestionando las estancias en un país extranjero y supervisando el cumplimiento de los requisitos del visado de estudiante. Sus capacidades de planificación de viajes futuros te permiten organizar tus viajes de manera eficiente, garantizando un equilibrio entre tus estudios y la exploración o las visitas a tu hogar.",

    about_page :  "Acerca de",

    contact_support: "Soporte dentro de la aplicación",
    contact_text : "Si ya eres usuario de la aplicación Flamingo, te recomendamos que te pongas en contacto con nosotros a través de los ajustes de la aplicación para que podamos ayudarte mejor.",
    contact_go_to : "Ir a la aplicación",
    contact_dsc : "Utiliza este formulario para completar una solicitud de asistencia o enviarnos tus comentarios.",
    contact_name : "Tu nombre",
    contact_email: "Dirección de correo electrónico",
    contact_model : "Modelo de iPhone",
    contact_select_model : "Seleccionar modelo",
    contact_version : "Versión de iOS",
    contact_select_version : "Seleccionar versión",
    contact_message : "Mensaje",
    contact_message_placeholder : "Escribe tu mensaje",
    contact_submit : "Enviar",
    contact_send_result : "¡Enviado!",
    contact_send_text : "¡Gracias por tu mensaje! Alguien de nuestro equipo se pondrá en contacto contigo en breve.",

    error_text: "Algo ha ido mal. Por favor, inténtalo de nuevo.",
    error_try: "Intentar de nuevo",
    error_email: "Introduce tu dirección de correo electrónico en el formato adecuado: {'tunombre@empresa.com'}",
    error_name: "Por favor, escribe tu nombre",
    to_upload : "Haz clic aquí",
    or_drop: "o arrastra y suelta para cargar archivos",

    blog_back : "Volver a los artículos",
    blog_stories: "Historias y entrevistas",
    blog_text_2 : "Las últimas noticias, consejos de viaje y trucos de nuestro equipo.",
    blog_related : "Publicaciones relacionadas",
    blog_text : "Las últimas noticias, consejos de viaje y trucos de nuestro equipo.",
    blog_view_all : "Ver todas las publicaciones",
    blog_published : "Publicado",

    page: "Página",
    go_back : "Volver"

}
