export default {
    ourusers: 'Our users',
    features: 'Features',
    security: 'Security',
    blog: 'Blog',
    contact_support_link: 'Contact Support',
    contact_us: 'Contact us',
    privacy_notice: 'Privacy Policy',
    terms_of_use: 'Terms of Use',
    support: 'Support',
    cookies: 'Cookies',
    accessibility: 'Accessibility',

    footer_text: "Flamingo App provides trip data, visa status and calculations for informational purposes only.",
    footer_text2: "It does not constitute legal, tax, or immigration advice—always consult a qualified professional. Flamingo App accepts no liability for actions taken based on the app’s data.",

    footer_made_in: "Made in the U.K.",
    footer_copyright: "© 2022—2025 AccuraSoft Ltd. Registered in England.",
    footer_copyright2: "CRN 12461952. VAT GB354336794. All right reserved.",
    footer_copyright3: "Flamingo App is a trademark of AccuraSoft Ltd.",


    pagination_prev: "Previous",
    pagination_next: "Next",

    download: "Download",
    download_now: "Flamingo Now",
    download_text: "An essential tool for global expats, permanent residents, dual-state residency and frequent travelers.",

    faq: "Frequently Asked Questions",
    faq_short: "FAQ",
    faq_text: "Find quick answers to common questions about using the Flamingo app.",
    faq_q1: 'Why do I need to set Location Services to "Always"?',
    faq_q2: "Why do I have to open the app every month?",
    faq_q3: "Can you see my precise location at any given time?",
    faq_q4: "Can I add my past travel history from before I installed the app?",
    faq_q5: "Can I use Flamingo for free?",
    faq_q6: "Can I track my travel to individual UK countries (England, Scotland, Wales, Northern Ireland) separately from the UK?",
    faq_q7: "Do you have an Android version?",

    faq_a1: 'For accurate automatic travel tracking, it\'s essential to set Location Services to "Always" instead of "While Using the App." This ensures Flamingo can track your movements in the background, even when the app is closed, eliminating the need to open the app each time you cross a country or state border. Rest assured, extensive testing has been conducted to ensure minimal battery usage with this location setting.',
    faq_a2: 'We recommend opening the app approximately every month, as the iPhone operating system may block an app’s tracking feature due to inactivity. Regularly opening Flamingo ensures continuous and accurate travel tracking without interruption.',
    faq_a3: 'Rest assured, all data entered or automatically recorded in the app is encrypted by Apple and stored solely on your device or Apple\'s secure data services (iCloud), depending on your app settings. We do not have access nor store your data on our servers and that is why we do not require registration in the app. Moreover, Flamingo never tracks your precise location. Instead, we use city-level geolocation to determine your general location for the purpose of recording your movements between countries, US states and cities. This approach ensures complete privacy for you and barely has any impact on your battery power. ',
    faq_a4: 'Yes, you can add your past travel information to the app. There are two ways to do this: manually add each trip to your timeline one-by-one, or if you usually take many photos, you can automatically reconstruct your travel history by scanning your Photo Library. We do not upload or see any of your photos; we only scan their location and timestamp information, so the scanning process takes just a few minutes.',
    faq_a5: "As a free user of the Flamingo app, you are allowed to enter up to five travel entries. This includes both manually entered trips (completed trips) and automatically tracked trips (new trips). Once you reach this limit, you will need to either delete some of the existing entries to add new ones or consider upgrading to a paid subscription for unlimited trip tracking and report feature.",
    faq_a6: "Yes, you have the option to track individual UK countries (England, Scotland, etc.) separately or combine them and record all visits as the UK. Additionally, you can track your visits to the islands of Jersey and Guernsey separately from mainland UK.",
    faq_a7: "The Flamingo app is not yet available on Android, but we are actively working on its development. Stay tuned for updates!",

    features_title: "Features",
    features_10reasons: "The Ultimate Travel Tracker",
    features_10reason_text: "An essential tool for global expats, permanent residents, overseas homeowners and frequent travelers.",
    features_auto: "Auto",
    features_record: 'Trip Recording',
    features_record_text: "Flamingo automatically determines when you cross the border and accurately records your trip details. You can always review your travel timeline in the app and make adjustments for transits as needed.",

    features_plan: "Plan Future Travel",
    features_plan_title: "Plan Future Travel",
    features_plan_subtitle: "Plan out your whole year by adding upcoming trips to the app. Once you’re there, Flamingo will track your movements and adjust dates as needed.",
    features_plan_text: "",

    features_store: "Store Documents and Trip Details",
    features_store_title: "Store Documents and Trip Details",
    features_store_subtitle: "Keep your trips organized by adding detailed notes and storing all relevant documents in one place. This is especially useful if you need to present proof of your travels to lawyers, tax advisors, or government authorities.",
    features_store_text: "",

    features_residency: "Tax Residency",
    features_dom_status: "Domicile Status",

    features_dom_text: "Whether you’re looking to establish, maintain or avoid a domicile or tax residency status, Flamingo got you covered. Set up a threshold and tracking period and monitor your physical presence in the country or US state. Receive timely alerts about your status to always stay on top of your tax obligations.",
    features_tax: "Tax",
    features_tax_residency: "Residency",
    features_tax_title: "Tax Residency Assessment",
    features_tax_subtitle: "Flamingo automatically determines the likelihood of your acquiring a tax residency status in most countries, US states and cities based on international tax rules. The tax residency assessment is based on physical presence, as well as additional criteria commonly used by local authorities, such as your income, property, and family ties.",
    features_tax_text: "",

    features_assessment: "Assessment",

    features_coming_soon: "Coming soon",
    features_usa: "US City & State",
    features_day_count: "Day Count",
    features_usa_text: "Flamingo auto-tracks your days in every US state and your workdays in key cities. You can select residency-eligible days, mark non-work days, and receive warnings as you approach residency status.",
    features_usa_text_2: "*Currently available only for New York City, NY. Other cities coming soon.",
    features_schengen: "Schengen Area",
    features_calculator: "Calculator",
    features_calculator_text: "Flamingo’s built-in Schengen calculator uses your cumulative days spent in Schengen countries to display days you have left and allows you to plan future trips to the EU based on the 90/180 day rule.",

    features_short_term: "Short-Term Visa Tracking",
    features_short_term_title: 'Short-Term Visas Tracking ',
    features_short_term_subtitle: 'Add your short-term visa details and visa-free access conditions, and the Flamingo app will automatically track your entries and stays in the country, alerting you as you approach your limits.',
    features_short_term_text: '',

    features_new_york: "Long-Term Visa & Residence Permit Tracking",
    features_new_york_title: "US Cities Day Count",
    features_new_york_subtitle: 'Track days in a country where you hold a long-term visa or residence permit for work, study, family or other immigration purpose. You can set multiple tracking rules, such as presence or absence caps for different reporting periods, store document details, and receive alerts as you near any limit or expiry date.',
    features_new_york_text: "",

    features_build_in: "Passport Index",
    features_build_in_title: 'Passport Index',
    features_build_in_subtitle: 'Look up visa requirements for any country by entering your citizenship(s) into the app. Find out where you can travel visa-free, or if you need a paper visa, e-visa, or visa on arrival. This tool simplifies your travel planning, ensuring you\'re always prepared for your next destination.',
    features_build_in_text: 'Note: This information is for general guidance only and should not be considered legal advice. Always consult with official sources before making travel plans.',

    features_export: "Export",
    features_reports: "Reports",
    features_reports_title: "Export Reports",
    features_reports_subtitle: "Export customizable CSV reports detailing your travel history for domicile and residency. These reports, developed in consultation with lawyers and tax advisors, ensure ease of tax filing and immigration compliance. Share them with authorities and legal professionals to simplify your documentation needs.",
    features_reports_text: "",

    how_security: "Security",
    how_text: "Your Privacy is Our Priority",
    how_important: "Important",
    how_notifications: "Notifications",
    how_notify_text: "Flamingo alerts you when you are reaching your residency threshold, visa-free stay limits,or visa expiration dates, helping you avoid any issues with authorities.",
    how_privacy: "Privacy",
    how_complete: "Complete",
    how_complete_text: "Your travel, residency and visa data is stored locally only on your device. We do not collect, nor store, your information on our servers. ",
    how_complete_text2: "*With Flamingo PRO you can sync your data via iCloud across all your devices.",
    how_bank_level: "Bank-Level",
    how_data_security: "Data Security",
    how_bank_text: "Flamingo employs multiple layers of data backups, guaranteeing peace of mind for your valuable travel information.",

    help_you: "Flamingo helps you with:",
    help1: 'USA Substantial Presence Test and Physical Presence Test',
    help2: 'UK Statutory Residence Test (SRT)',
    help3: 'EU Schengen Area tracking, 90 in 180 days rule',
    help4: 'France Tax Residency Test',
    help5: 'Switzerland 90-day rule',
    help6: 'Canada residence / physical presence requirements',
    help7: 'Puerto Rico Act 60 (act 20/22) day counting',
    help8: 'India residence status day counting',
    help9: 'Malaysia residence status day counting',
    help10: 'South Africa’s physical presence rule',
    help11: 'Cyprus residency day counting',
    help12: 'Israel residency',
    help13: 'Italy 183-day rule, Australia 183-day rule, Spain 183-day rule, Brazil 183-day rule',
    help14: 'New Zealand 325-day rule',
    help15: 'Cyprus 60-day rule',

    index_who_need: "Who needs Flamingo?",
    index_expats: "Expats &",
    index_expats_nomads: "Digital Nomads",
    index_expats_texts: "Flamingo keeps tabs on the number of days and nights spent in your country of residence, proving to be an essential tool for global expats, overseas homeowners, digital nomads, and permanent residents looking for an efficient way to manage their residency obligations.",
    index_tax: "Tax",
    index_residents: "Residents",
    index_residents_text: "The Flamingo app simplifies tax residency management by automatically tracking your travel days and alerting you when nearing residency thresholds. It also provides detailed, expert-developed reports for easy sharing with authorities, tax consultants and accountants.",
    index_frequent_travelers: "Frequent Travelers",
    index_ft_text: "Flamingo automatically records your border crossings into different countries and US states, while diligently tracking your visas and visa-free stay limits. Whether you travel for business or leisure, the app allows you to view and manage your trip history, add details, and plan upcoming journeys. ",
    index_i: "International",
    index_s: "Students",
    index_is_text: "Flamingo simplifies life for international students by managing stays in a foreign country and overseeing adherence to student visa requirements. Its future trip planning capabilities allow you to organize your travels efficiently, ensuring a balance between your studies and exploration or home visits.",

    about_page: "About",

    contact_support: "In-App Support",
    contact_text: "If you are an existing Flamingo app user, we recommend contacting us through the app settings, so that we will be better equipped to assist you",
    contact_go_to: "Go to the App",
    contact_dsc: "Use this form to complete a support request or send us your feedback.",
    contact_name: "Your Name",
    contact_email: "Email address",
    contact_model: "iPhone Model",
    contact_select_model: "Select Model",
    contact_version: "iOS Version",
    contact_select_version: "Select Version",
    contact_message: "Message",
    contact_message_placeholder: "Enter your message",
    contact_submit: "Submit",
    contact_send_result: "Sent!",
    contact_send_text: "Thank you for your message! Someone from our team will reach out to you soon.",

    error_text: "Something went wrong. Please try again.",
    error_try: "Try Again",
    error_email: "Please enter your email address in proper format: yournameAtcompany.com",
    error_name: "Please enter your name",
    to_upload: "Click here",
    or_drop: "or drag and drop to upload files",

    blog_back: "Back to the Articles",
    blog_stories: "Stories and interviews",
    blog_text_2: "The latest news, travel tips, and tricks from our team.",
    blog_related: "Related Posts",
    blog_text: "The latest news, travel tips, and tricks from our team.",
    blog_view_all: "View all posts",
    blog_published: "Published",

    page: "Page",
    go_back: "Go back",



    anim_stap1_title: 'Overseas and Stateside Travel App',
    anim_stap1_text: 'Automated travel days tracker designed for tax residency, visa, and immigration compliance.',

    anim_stap2_title: 'Your Travels, Simplified',
    anim_stap2_text: 'Effortlessly track trips, monitor visa days, and stay compliant, all at your fingertips. Designed to adapt to your lifestyle, wherever you go.',

    anim_stap3_title: 'Auto Trip Recording',
    anim_stap3_text: 'Flamingo travels with you and automatically records your movements between countries, US states and select US cities.',

    anim_stap4_title1: 'Schengen',
    anim_stap4_title2: 'Calculator',
    anim_stap4_text: 'Easily comply with the Schengen 90/180 rules when traveling around Europe with the Flamingo Schengen area calculator.',


    anim_stap5_title: 'Tax Residency & Domicile',
    anim_stap5_text: 'Keep track of your domicile and tax residency status with timely alerts and important updates.',
    anim_stap5_noti_title: 'Flamingo',
    anim_stap5_noti_subtitle: 'You’ve achieved tax residency!',
    anim_stap5_noti_now: 'Now',


    anim_stap6_title: 'US Cities Day Count',
    anim_stap6_text: 'Count days and track your residency status in select US cities to comply with local tax regulations.',
    anim_stap6_noti_title: 'Flamingo',
    anim_stap6_noti_subtitle: '3 days left to reach tax residency in New York, NY. Plan ahead!',
    anim_stap6_noti_now: 'Now',

    anim_stap7_title: 'Passport Index',
    anim_stap7_text: 'Check visa requirements for your next trip by adding your citizenship, with real-time updates synced to the IATA database.',
    anim_stap7_btn_title: 'View All Features',




}
