export default {
    forwhom: 'Our users',
    features: 'Features',
    'how-it-works': 'Security',
     blog: 'Blog',
    'contact_us': 'Contact us',
    'privacy_notice' : 'Privacy Notice',
    'terms_of_use' : 'Terms of Use',
    'support': 'Support',
    'Support': 'Support',
    footer_text : "Flamingo tracking and counting are created for information purposes only.",
    footer_text2 : "Always consult with your legal advisor about specific requirements for your residency and visa status.",

    'footer_made_in': "Made in the U.K",
    footer_copyright: "©2022 — 2024 Taboo Media Limited. Registered in England",
    footer_copyright2: "Company number: 12461952. All rights reserved.",
    footer_copyright3: "Flamingo App is a trademark of Taboo Media Limited.",


    pagination_prev : "Previous",
    pagination_next: "Next",

    download : "Download",
    download_now : "Flamingo Now",
    download_text : "An essential tool for global expats, permanent residents, overseas homeowners and frequent travelers.",

    faq : "Frequently Asked Questions",
    faq_text : "Everything you need to know.",
    faq_q1 : "What is Flamingo Tracker 1?",
    faq_q2 : "What is Flamingo Tracker 2?",
    faq_q3 : "What is Flamingo Tracker 3?",
    faq_q4 : "What is Flamingo Tracker 4?",
    faq_q5 : "What is Flamingo Tracker 5?",
    faq_q6 : "What is Flamingo Tracker 6?",

    faq_a1:  "Flamingo automatically keeps Flamingo automatically keeps Flamingo automatically keeps Flamingo automatically keepsFlamingo automatically keeps tabs on the number of nights/days spent in your country of residence and away. A useful tool for global expats, overseas homeowners, digital nomads and permanent residents.",
    faq_a2:  "Flamingo automatically keeps tabs on the number of nights/days spent in your country of residence and away. A useful tool for global expats, overseas homeowners, digital nomads and permanent residents.",
    faq_a3:  "Flamingo automatically keeps tabs on the number of nights/days spent in your country of residence and away. A useful tool for global expats, overseas homeowners, digital nomads and permanent residents.",
    faq_a4:  "Flamingo automatically keeps tabs on the number of nights/days spent in your country of residence and away. A useful tool for global expats, overseas homeowners, digital nomads and permanent residents.",
    faq_a5:  "Flamingo automatically keeps tabs on the number of nights/days spent in your country of residence and away. A useful tool for global expats, overseas homeowners, digital nomads and permanent residents.",
    faq_a6:  "Flamingo automatically keeps tabs on the number of nights/days spent in your country of residence and away. A useful tool for global expats, overseas homeowners, digital nomads and permanent residents.",

    features_title : "Features",
    features_10reasons : "10 reasons to Use Flamingo",
    features_10reason_text : "An essential tool for global expats, permanent residents, overseas homeowners and frequent travelers.",
    features_auto : "Auto",
    features_record : 'Trip Recordingt',
    features_record_text  : "Flamingo automatically determines if you have left your residence country or state and accurately records your trip details.",
    features_plan : "Plan future trips",
    features_store: "Store documents and trip details",
    features_residency : "Residency",
    features_dom_status : "Domicile Status",
    features_dom_text : "Flamingo helps you establish your country of residence and domicile by automatically counting your days and nights in and out of the country.",
    features_tax :"Tax",
    features_assessment: "Assessment",
    features_coming_soon: "Coming soon",
    features_usa : "USA States",
    features_day_count : "Day Count",
    features_usa_text : "Flamingo shows how many combined days you’ve already spent in Schengen countries and how many more you have left in the 180-day period.",
    features_schengen : "Schengen Area",
    features_calculator: "Calculator",
    features_calculator_text : "Flamingo shows how many combined days you’ve already spent in Schengen countries and how many more you have left in the 180-day period.",
    features_short_term : "Short-Term Visa Tracking",
    features_new_york : "New York City Day Count",
    features_build_in : "Built-In Passport Index",
    features_export : "Export",
    features_reports : "Reports",

    how_security: "Security",
    how_text : "Your Safety is Our Priority",
    how_important : "Important",
    how_notifications : "Notifications",
    how_notify_text : "Flamingo notifies you when you are reaching your stay limits or your visa is about to expire, so that you don’t get in trouble with authorities. ",
    how_privacy : "Privacy",
    how_complete: "Complete",
    how_complete_text : "Your travel, residency and visa data is stored locally only on your device. We do not collect, nor store, your information on our servers.",
    how_complete_text2 : "With Flamingo PRO you can sync your data via iCloud across all your devices.",
    how_bank_level  : "Bank-Level",
    how_data_security : "Data Security",
    how_bank_text : "Flamingo employs multiple layers of data backups, guaranteeing peace of mind for your valuable travel information.",

    help_you : "Flamingo Helps You with",
    help1 : 'USA Substantial Presence Test and Physical Presence Test',
    help2 : 'USA Substantial Presence Test and Physical Presence Test',
    help3 : 'UK Statutory Residence Test',
    help4 :'UK Statutory Residence Test',
    help5: 'EU Schengen Area tracking, 90 in 180 days rule',
    help6: 'Cyprus residency day counting',
    help7: 'Canada residence / physical presence requirements',
    help8: 'Israel residency',
    help9: 'Puerto Rico Act 60 (act 20/22) day counting',
    help10:'The international 183-day rule',
    help11:'India residence status day counting',
    help12:'Tracking of permitted visa stay time and expiration date to prevent overstays',
    help13:'International health insurance for expats',
    help14:'US & UK tax residency requirements',

    index_from_whom : 'For Whom',
    index_who_need : "Who needs Flamingo?",
    index_expats: "Expats",
    index_expats_texts : "Flamingo automatically keeps tabs on the number of nights/days spent in your country of residence and away. A useful tool for global expats, overseas homeowners, digital nomads and permanent residents.",
    index_tax : "Tax",
    index_residents : "Residents",
    index_residents_text : "Flamingo helps you establish your country of residence by automatically counting your days and nights in and out of the country.",
    index_frequent_travelers : "Frequent Travelers",
    index_ft_text : "Flamingo flies with you and automatically records when you cross the border to enter another country. You can view your trip history and see the number of days you’ve spent in a country. The app automatically calculates how many more days you have left based on your visa or passport details.",
    index_i : "International",
    index_s : "Students",
    index_is_text : "Use Flamingo to maintain your student status and comply with your visa regulations.",

    about_page :  "About",

    contact_support: "In-App Support",
    contact_text : "If you are an existing Flamingo app user, we recommend contacting us through the app settings. That way we will be better equipped to help you.",
    contact_go_to : "Go to the App",
    contact_dsc : "Use this form to complete a support request or send us your feedback.",

    blog_back : "Back to the Articles",
    blog_stories: "Stories and interviews",
    blog_text_2 : "The latest news, travel directions, tips and tricks from our team.",
    blog_related : "Related Posts",
    blog_text : "The latest news, travel directions, tips and tricks from our team.",
    blog_view_all : "View all posts",
    blog_published : "Published",

    page: "Page"





}
