export default {
    ourusers: '我们的用户',
    features: '功能',
    security: '安全性',
    blog: '博文',
    contact_support_link: '联系支持团队',
    contact_us: '联系我们',
    privacy_notice : '隐私告知',
    terms_of_use : '使用条款',
    support: '支持',
    footer_text : "Flamingo跟踪和计数仅供参考。",
    footer_text2 : "请务必咨询您的法律顾问和税务咨询公司，了解您的居留和签证身份的具体要求。",

    footer_made_in: "英国出品",
    footer_copyright: "©2022 — 2025年 AccuraSoft Ltd。注册于英格兰",
    footer_copyright2: "公司登记号：12461952。版权所有。",
    footer_copyright3: "Flamingo应用程序为AccuraSoft Ltd。的商标。",


    pagination_prev : "上一个",
    pagination_next: "下一个",

    download : "下载",
    download_now : "即刻使用Flamingo",
    download_text : "全球外籍人士、永久居民、双重国籍居民和频繁旅行者必不可少的工具。",

    faq : "常见问题解答",
    faq_short : "常见问题",
    faq_text : "查找有关使用Flamingo应用程序的常见问题的简要答案。",
    faq_q1 : '为何要将“位置服务”设置为“始终使用”？',
    faq_q2 : "为何每月都要打开一次应用程序？",
    faq_q3 : "你们是否任何时候都能看到我的确切位置？",
    faq_q4 : "是否能够添加安装应用程序之前的过往旅行记录？",
    faq_q5 : "Flamingo能否免费使用？",
    faq_q6 : "从英国开始的旅行是否可以按英格兰、苏格兰、威尔士、北爱尔兰分别记录？",
    faq_q7 : "你们提供安卓版本吗？",

    faq_a1:  '为了实现准确的自动旅行跟踪，将位置服务设置为“始终使用”而不是“使用应用程序时”至关重要。这确保了Flamingo可以在后台跟踪您的移动，即使应用程序关闭，也不需要每次穿越国家或州边界时都打开应用程序。请放心，我们已经进行了广泛的测试，以确保在此位置设置下电池使用量最小。',
    faq_a2:  '我们建议大约每月打开一次应用程序，因为iPhone操作系统可能会因不活动而阻止应用程序的跟踪功能。定期打开Flamingo可确保连续准确的旅行跟踪，不至于发生中断。',
    faq_a3:  '请放心，应用程序中输入或自动记录的所有数据均由Apple加密，并仅存储在您的设备或Apple的安全数据服务（iCloud）上，具体取决于您的应用程序设置。我们无法访问您的数据，也无法将其存储在我们的服务器上，这就是为什么我们不需要您在应用程序中注册。此外，Flamingo永远不会跟踪你的精确位置。相反，我们使用城市级地理定位来确定您的大致位置，以便记录您在不同国家、美国各州和城市之间的移动。这种方法确保了您的完全隐私，对您的电池电量几乎没有任何影响。',
    faq_a4:  '是的，您可以将过去的旅行信息添加到应用程序中。有两种方法可以做到这一点：手动将每次旅行逐一添加到您的时间线中，或者如果您通常拍摄许多照片，您可以通过扫描照片库自动重建您的旅行历史。我们不会上传或看到您的任何照片；我们只扫描它们的位置和时间戳信息，因此扫描过程只需要几分钟。',
    faq_a5:  "作为Flamingo应用程序的免费用户，您最多可以输入五个旅行条目。这包括手动输入的行程（已完成的行程）和自动跟踪的行程（新行程）。一旦达到此限制，您将需要删除一些现有条目以添加新条目，或者考虑升级到付费订阅，以获得无限制的行程跟踪和报告功能。",
    faq_a6:  "是的，您可以选择单独跟踪单个英国地区（英格兰、苏格兰等），也可以将其合并，并将所有访问记录为英国。此外，您可以分别跟踪从英国本岛到泽西岛和根西岛的访问。",
    faq_a7:  "Flamingo应用程序尚无法在安卓设备上使用，但我们正在积极开发。请继续关注更新！",

    features_title : "功能",
    features_10reasons : "终极旅行跟踪软件",
    features_10reason_text : "全球外籍人士、永久居民、在海外拥有房产者和频繁旅行者必不可少的工具。",
    features_auto : "自动",
    features_record : '旅行记录',
    features_record_text  : "Flamingo会自动判断您何时越过边境，并准确记录您的旅行细节。 ",

    features_plan : "计划未来旅行",
    features_plan_title : "计划未来旅行",
    features_plan_subtitle : "通过在应用程序中添加即将到来的旅行来对全年进行规划。一旦您到了那里，Flamingo会跟踪您的行踪，并根据需要调整日期。",
    features_plan_text : "",

    features_store: "存储文件和旅行详细信息",
    features_store_title: "存储文件和旅行详细信息",
    features_store_subtitle: "通过添加详细的笔记并将所有相关文件存储在一个地方来让您的旅行井井有条。如果您需要向律师、税务顾问或政府当局出示旅行证明，这尤其有用。",
    features_store_text: "",

    features_residency : "居留",
    features_tax_residency : "居留",
    features_dom_status : "居住地状态",

    features_dom_text : "无论您是想获得、维持还是避免居住地或居留身份，Flamingo都能为您提供支持。设置一个阈值和跟踪期，并监控您身处该国或美国各州的情况。",
    features_tax :"税务",
    features_tax_title: "税务居民评估",
    features_tax_subtitle: "Flamingo会根据国际税收规则自动确定您在大多数国家、美国州和城市获得税务居民身份的可能性。税务居民评估基于您实际身处何处，以及地方当局常用的其他标准，如您的收入、财产和家庭关系。",
    features_tax_text: "",

    features_assessment: "评估",

    features_coming_soon: "即将推出",
    features_usa : "美国各州",
    features_day_count : "天数统计",
    features_usa_text : "如果您是跨州居民，或者只是经常在美国各州之间旅行，Flamingo将自动记录并计算您在每个州度过的天数，以确定您的居住地和州居民的实际情况。",
    features_schengen : "申根地区",
    features_calculator: "计算器",
    features_calculator_text : "Flamingo的内置申根计算器使用您在申根国家的累计天数来显示您剩余的天数，并允许您根据90/180天的规则计划未来前往欧盟的旅行。",

    features_short_term : "短期签证跟踪",
    features_short_term_title : '短期签证跟踪 ',
    features_short_term_subtitle : '添加您的短期签证详细信息和免签证入境条件，Flamingo应用程序将自动跟踪您在该国的入境和停留情况，并在天数快满时提醒您。',
    features_short_term_text : '',

    features_new_york : "美国城市天数统计",
    features_new_york_title : "美国城市天数统",
    features_new_york_subtitle : '我们认识到遵守美国州和地方城市税收法规的重要性，这就是为什么我们现在为美国各个城市提供单独的天数跟踪。例如，您可以设置税务居住地，并跟踪您对纽约市五个行政区（曼哈顿、布鲁克林、皇后区、布朗克斯和史坦顿岛）的访问，这与您在纽约州的逗留无关。\n\n我们不断将更多美国城市添加到应用程序中，以增强您的体验。',
    features_new_york_text : "",

    features_build_in : "护照指数",
    features_build_in_title : '护照指数',
    features_build_in_subtitle : '通过在应用程序中输入您的公民身份，查找任何国家的签证要求。了解您可以在哪里免签证旅行，或者您是否需要纸质签证、电子签证或落地签证。此工具简化了您的旅行计划，确保您始终为下一个目的地做好准备。',
    features_build_in_text: '注：此信息仅供一般指导，不应被视为法律建议。在制定旅行计划之前，请务必咨询官方消息来源。',

    features_export : "导出",
    features_reports : "报告",
    features_reports_title : "导出报告",
    features_reports_subtitle : "导出可定制的CSV报告，详细说明针对居住地和居留权的旅行历史。这些报告是在与律师和税务顾问协商后开发的，确保了税务申报和移民合规的便利性。与当局和法律专业人士分享，以简化您的文档需求。",
    features_reports_text : "",

    how_security: "安全性",
    how_text : "您的隐私是我们的头等大事",
    how_important : "重要",
    how_notifications : "通知",
    how_notify_text : "Flamingo会在您达到居留门槛、免签证逗留限制或签证到期日期时提醒您，帮助您避免与当局发生任何问题。",
    how_privacy : "隐私",
    how_complete: "完完全全",
    how_complete_text : "您的旅行、居留和签证数据仅存储在您的设备上。我们不会在我们的服务器上收集或存储您的信息。",
    how_complete_text2 : "*使用Flamingo PRO，您可以通过iCloud在所有设备上同步数据。",
    how_bank_level  : "银行级别",
    how_data_security : "数据的安全性",
    how_bank_text : "Flamingo采用多层数据备份，保证您不用担心宝贵的旅行信息。",

    help_you : "Flamingo可在以下方面为您提供帮助：",
    help1: '美国实质性存在测试和实际存在测试',
    help2: '英国法定居留测试（SRT）',
    help3: '欧盟申根区追踪，180天内90天规则',
    help4: '法国税务居民测试',
    help5: '瑞士90天规则',
    help6: '加拿大居住/实际存在要求',
    help7: '波多黎各第60号法案（第20/22号法案）天数统计',
    help8: '印度居留身份天数统计',
    help9: '马来西亚居留身份天数统计',
    help10: '南非实际存在规定',
    help11: '塞浦路斯居留权天数统计',
    help12: '以色列居留权',
    help13: '意大利183天规则、澳大利亚183天规则、西班牙183天规则、巴西183天规则',
    help14: '新西兰325天规则',
    help15: '塞浦路斯60天规则',

    index_who_need : "谁需要Flamingo？",
    index_expats: "外籍人士和",
    index_expats_nomads : "数字游民",
    index_expats_texts : "Flamingo会记录您在居住国度过的昼夜数，这被证明是全球外籍人士、海外房主、数字游民和永久居民寻求有效管理其居留义务的重要工具。",
    index_tax : "税务",
    index_residents : "居民",
    index_residents_text : "Flamingo应用程序通过自动跟踪您的旅行天数并在接近居住阈值时提醒您，简化了税务居住管理。它还提供详细的、专家开发的报告，以便与政府部门、税务顾问和会计师轻松共享。",
    index_frequent_travelers : "频繁旅行者",
    index_ft_text : "Flamingo会自动记录您进入不同国家和美国各州的过境情况，同时认真跟踪您的签证和免签证逗留限制。无论您是商务旅行还是休闲旅行，该应用程序都可使您查看和管理您的旅行历史记录，添加详细信息，并计划即将到来的旅行。",
    index_i : "国际",
    index_s : "学生",
    index_is_text : "Flamingo通过管理在国外的逗留和监督学生签证要求的遵守情况，简化了国际学生的生活。它未来的旅行计划功能使您能够高效地组织旅行，确保您在学习、探访或探亲之间取得平衡。",

    about_page :  "关于我们",

    contact_support: "应用程序内支持",
    contact_text : "如果您是现有的Flamingo应用程序用户，我们建议您通过应用程序设置与我们联系，以便我们能够更好地为您提供帮助",
    contact_go_to : "前往应用程序",
    contact_dsc : "使用此表格填写支持请求或向我们发送您的反馈。",
    contact_name : "您的姓名",
    contact_email: "电子邮件地址",
    contact_model : "iPhone型号",
    contact_select_model : "选择型号",
    contact_version : "iOS版本",
    contact_select_version : "选择版本",
    contact_message : "信息",
    contact_message_placeholder : "输入信息",
    contact_submit : "提交",
    contact_send_result : "已发出！",
    contact_send_text : "感谢您的来信！我们的团队成员将尽快联系您。",

    error_text: "出错了。请再试一次。",
    error_try: "再试一次",
    error_email: "请以正确格式输入邮件地址，如：yournameAtcompany.com",
    error_name: "请输入您的姓名",
    to_upload : "点击这里",
    or_drop: "或拖放文件上传",

    blog_back : "返回“文章”",
    blog_stories: "故事和访谈",
    blog_text_2 : "来自我们团队的最新消息、旅行提示和窍门。",
    blog_related : "相关帖子",
    blog_text : "来自我们团队的最新消息、旅行提示和窍门。",
    blog_view_all : "查看所有帖子",
    blog_published : "已发布",

    page: "页",
    go_back : "返回"



}
